
version: "3.9"

services:
  api-gateway:
    build:
      context: ./backend/api-gateway
    image: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - stability-service
      - viscosity-service

  stability-service:
    build:
      context: ./backend/stability-service
    image: stability-service
    ports:
      - "8002:8002"
    environment:
      - DEEPSTABP_API_PATH=/app/deepStabP/src/Api
      - DEEPSTABP_MODEL_REF=/app/deepStabP/models/Rostlab/prot_t5_xl_uniref50
    volumes:
      - ./deepStabP:/app/deepStabP:ro
      - stability_hf_cache:/app/hf_cache

  viscosity-service:
    build:
      context: ./backend/viscosity-service
    image: viscosity-service
    ports:
      - "8003:8003"
    environment:
      - DEEPPATH=/app/DeepViscosity
    volumes:
      - ./DeepViscosity:/app/DeepViscosity

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

volumes:
  stability_hf_cache:
